# Generated by Django 5.0.7 on 2024-07-22 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decorations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('remaining', models.FloatField(default=0, verbose_name='Remaining')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='^(\\+370|8)\\d{8}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('remaining', models.FloatField(default=0, verbose_name='Remaining')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='WrappingPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('remaining', models.FloatField(default=0, verbose_name='Remaining')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.phonemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.client')),
                ('decoration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.decorations')),
                ('roses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
                ('wrappingpaper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.wrappingpaper')),
            ],
        ),
    ]
