# Generated by Django 5.0.7 on 2024-07-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone_number',
            new_name='client_phone_number',
        ),
    ]
