# Generated by Django 5.0.7 on 2024-07-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_phone_number_client_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='decoration_qty',
            field=models.IntegerField(default=0, verbose_name='Decorations Quantity'),
        ),
        migrations.AddField(
            model_name='order',
            name='roses_qty',
            field=models.IntegerField(default=0, verbose_name='Roses Quantity'),
        ),
        migrations.AddField(
            model_name='order',
            name='wp_qty',
            field=models.IntegerField(default=0, verbose_name='Wrapping Paper Quantity'),
        ),
    ]
