# Generated by Django 5.0.7 on 2024-07-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_decoration_qty_order_roses_qty_order_wp_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrappingpaper',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
