# Generated by Django 5.0.7 on 2024-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_wrappingpaper_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorations',
            name='price',
            field=models.FloatField(default=0.49, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=1.3, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='wrappingpaper',
            name='price',
            field=models.FloatField(default=0.25, verbose_name='Price'),
        ),
    ]
